name: Download v2rayN Releases

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch: # 手动触发

jobs:
  download-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get v2rayN releases
        id: get_release
        uses: joutvhu/get-release@v1.0.0
        with:
          repo: 2dust/v2rayN
          include: prereleases, releases

      - name: Download assets
        run: |
          mkdir -p v2rayN_assets
          echo "${{ steps.get_release.outputs.releases }}" | jq -r '.[] | .assets[] | .browser_download_url' | while read url; do
            wget -P v2rayN_assets "$url"
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add v2rayN_assets/
          git status  # 检查添加的文件状态
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            git commit -m "Downloaded v2rayN assets on $current_time"
            git pull --rebase origin main
            git push origin main
