name: Backup Binaries

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * */2 * *" # 每两天运行一次

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true  # 启用 LFS

      - name: Set timezone and current time
        run: |
          export TZ="Asia/Shanghai"
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          echo "current_time=${current_time}" >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get install -y aria2 jq

      - name: Download and setup 7zip
        run: |
          mkdir -p Archive
          cd Archive
          mkdir -p 7zip
          wget "https://www.7-zip.org/a/7z2301-linux-x64.tar.xz" -O 7zip/7zip.tar.xz
          tar -xf 7zip/7zip.tar.xz -C 7zip/ && mv 7zip/7zz .
          rm -rf 7zip && chmod +x 7zz

      - name: Download v2rayN assets
        run: |
          mkdir -p Archive/v2rayn/Clients
          cd Archive/v2rayn/Clients
          wget -qO- https://api.github.com/repos/2dust/v2rayN/releases/latest | jq -r ".assets[].browser_download_url" | xargs -n 1 -P 8 aria2c -x 16 -s 16

      - name: Download v2rayNG assets
        run: |
          mkdir -p Archive/v2rayng/Clients
          cd Archive/v2rayng/Clients
          wget -qO- https://api.github.com/repos/2dust/v2rayNG/releases/latest | jq -r ".assets[].browser_download_url" | xargs -n 1 -P 8 aria2c -x 16 -s 16

      - name: Install Git LFS
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
          sudo apt-get install git-lfs
          git lfs install

      - name: Configure Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Track large files with Git LFS
        env:
          current_time: ${{ env.current_time }}
        run: |
          git lfs track "*.zip"
          git lfs track "*.7z"
          git lfs track "*.apk"
          git add .gitattributes
          git commit -m "更新时间：${{ env.current_time }}"

      - name: Commit and push changes
        env:
          current_time: ${{ env.current_time }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Archive/
          git add .gitattributes
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git stash
            git pull --rebase origin main
            git stash pop
            git add Archive/
            git add .gitattributes
            git commit -m "更新时间：${{ env.current_time }}"
            git push origin main
          fi
