name: Backup Binaries

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron: "0 * */2 * *"

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Backup Binaries
        run: |
          export TZ="Asia/Shanghai"
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          echo "current_time=${current_time}" >> $GITHUB_ENV
          sudo apt install -y aria2
          mkdir Archive
          cd Archive
          # using 7zip
          mkdir -p 7zip
          wget "https://www.7-zip.org/a/7z2301-linux-x64.tar.xz" -O 7zip/7zip.tar.xz
          tar -xf 7zip/7zip.tar.xz -C 7zip/ && mv 7zip/7zz .
          rm -rf 7zip && chmod +x 7zz
          # v2rayn
          mkdir -p v2rayn/Clients
          pushd v2rayn/Clients || exit 1
          wget -qO- https://api.github.com/repos/2dust/v2rayN/releases/latest | jq ".assets[] | {browser_download_url}" -c | jq .browser_download_url -r | aria2c -c -x 8 -s 8 -j 1 -k 1M -i -
          popd || exit 1
          # v2rayng
          mkdir -p v2rayng/Clients
          pushd v2rayng/Clients || exit 1
          wget -qO- https://api.github.com/repos/2dust/v2rayNG/releases/latest | jq ".assets[] | {browser_download_url}" -c | jq .browser_download_url -r | aria2c -c -x 8 -s 8 -j 1 -k 1M -i -
          popd || exit 1

      - name: Commit and push changes
        env:
          current_time: ${{ env.current_time }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git stash
            git pull --rebase origin main
            git stash pop
            git add .
            git commit -m "更新时间：${{ env.current_time }}"
            git push origin main
          fi
