name: Fetch and Save XML Files For EPG

on:
  workflow_dispatch:
  watch:
    types: [started]
  schedule:
    - cron: "0 */2 * * *"

jobs:
  fetch_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Fetch XML files
        run: |
          export TZ="Asia/Shanghai"
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          echo "current_time=${current_time}" >> $GITHUB_ENV
          curl -o "pp.xml.gz" https://epg.112114.xyz/pp.xml.gz
          curl -o "e1.xml.gz" http://epg.51zmt.top:8000/e.xml.gz
          curl -o "e2.xml.gz" https://gitee.com/Black_crow/xmlgz/raw/master/all.xml.gz

      - name: Commit and push changes
        env:
          current_time: ${{ env.current_time }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status  # 检查添加的文件状态
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git stash
            git pull --rebase origin main
            git stash pop
            git status  # 检查工作目录状态
            git commit -m "更新时间：${{ env.current_time }}"
            git push origin main
          fi
