name: Fetch v2rayN Releases

on:
  schedule:
    - cron: '0 0 * * *' # 每天运行一次
  workflow_dispatch: # 手动触发

jobs:
  fetch-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install requests

      - name: Fetch v2rayN releases
        env:
          GITHUB_REPOSITORY: '2dust/v2rayN'
        run: |
          python fetch_releases.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add v2rayN_releases.json
          git status  # 检查添加的文件状态
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            git commit -m "更新时间：$current_time"
            git pull --rebase origin main
            git push origin main
